version: '3.8'
services:
  chinchilla-postgres:
    image: swift:5.8-focal
    volumes:
      - ..:/workspace
    command: sleep infinity

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chinchilla
      - POSTGRES_PASSWORD=chinchilla
      - POSTGRES_DB=chinchilla

volumes:
  postgres-data:
