name: "CI"
on: [push, pull_request]
jobs:
  soundness:
    name: Soundness Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Bootstrap Mint
        uses: irgaly/setup-mint@v1

      - name: Run soundness
        run: |
          scripts/soundness.sh
          exit $(git status --porcelain | wc -l)

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swift: [5.8, latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: ci
        ports:
          - 5432:5432
    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}

      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Cache Swift PM
        uses: actions/cache@v3.3.1
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.swift }}-spm-${{ hashFiles('Package.swift') }}
          restore-keys: ${{ runner.os }}-${{ matrix.swift }}-spm-

      - name: Resolve Swift dependencies
        run: swift package resolve

      - name: Run Integration Tests
        run: swift test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: ci
